### ISSUE TITLE
VercelからCloudflare Pagesに移行する

### ISSUE THREAD

**Issue by penpendayo** [praha-inc/about-us#37]
Vercelのページに[商用利用はダメだよ](https://vercel.com/docs/limits/fair-use-guidelines#commercial-usage)的なことが書いてるのに、採用サイトというド直球の商用利用（？）をしているため、[商用利用OK](https://community.cloudflare.com/t/cloudflare-pages-for-commercial-use/306890)のCloudflareに移行する。

```[tasklist]
### Tasks
- [ ] https://github.com/praha-inc/about-us/issues/38
- [ ] https://github.com/praha-inc/about-us/issues/39
- [ ] https://github.com/praha-inc/about-us/issues/82
- [ ] https://github.com/praha-inc/about-us/issues/186
- [ ] https://github.com/praha-inc/about-us/issues/83
```

**Comment by penpendayo** [comment]
終わったので閉じます

**Comment by penpendayo** [comment]
まだ終わってなかった

**Comment by penpendayo** [comment]
今度こそおわった
